### ISSUE TITLE
Divide and Remainder are missing overflow corner case test

### ISSUE THREAD

**Issue by davidharrishmc** [riscv-non-isa/riscv-arch-test#300]
The RISC-V specification Section 7.2 defines a corner case for divide and remainder for the most negative integer divided by -1.  

It appears that this case is not tested in div-01 and other divide and remainder tests.

**Comment by davidharrishmc** [comment]
I think patch #302 is relevant to issue #299, not #300.  I didn't see changes about divide and remainder corner cases in #302.

**Comment by allenjbaum** [comment]
You are correct that it fixes #299. It is a bit of a surprise to me that the most negative integer is caught by a walking one dividend and a walking zeroes divisor test, but it may not be looking for those simultaneously (or -1 might not be considered walking zero value.
 In the version of the unpriv spec Im looking at, section 7.2 has no mention of divide at all, it is now section 9.2

**Comment by davidharrishmc** [comment]
Allen, I think you might have meant "isn't caught" rather than "is caught".  In any case, I searched div-01.S for op2val:-0x1 and didn't find any hits, so I'm pretty sure the corner case is missing.

**Comment by allenjbaum** [comment]
Yes, you're correct, that should have been "isn't".
I think the tests are structured so they hit all walking 0s and walking 1 patterns - but not all crossproducts.
IF div didn't have any op2val=-1, then something went wrong.
There should be max[u/s]int/min[u/s]int combinations for that (e.g. 2^XLEN-1, -2^XLEN, 0,1,-1) for most tests.
If DIV has no tests with rs2 = -1, then something is buggy.

**Comment by allenjbaum** [comment]
Looking at div test inst_2:
// rs2 == rd != rs1, rs1==x26, rs2==x11, rd==x11, rs1_val < 0 and rs2_val < 0, rs1_val == -8193
// opcode: div ; op1:x26; op2:x11; dest:x11; op1val:-0x2001;  op2val:-0x1 <--
so it does test dividing by -1, but not with the max negative dividend.

**Comment by davidharrishmc** [comment]
Ah, -1 shows up in rv32_m/M/src/div-01.S but not in rv64_m/M/src/div-01.S.

I wonder why walking 1s doesn't produce the -1 case in rv64?

**Comment by allenjbaum** [comment]
I was wrong. Walking X always has at least one X in it (and -1 has no 0s in
it)
 But, looking at the code, both rs1 and rs2 should have generated a test
for every integer in the range -10..10.
But, looking at the test, -1,-2,-4,-8,+/-7, and +10 are missing.
In RV32, -6, +/-7, -8, +/-10, and  +9  are missing.
Clearly I'm not understanding something about how ctg works.
Even if it did, though, there's no guarantee it would have paired that with
the max negative number.
That special test needs to be added, in any case.

**Comment by pawks** [comment]
The coverpoints for which the tests have been generated can be found [here](htmlpreview.github.io/?https://github.com/riscv-non-isa/riscv-arch-test/blob/revert-294-canary-patch/riscv-test-stats/coverage/rv32i_m/M/coverage.html). If the coverpoint is not present in this file, then the test will not contain the corresponding test case. For `-1` there is no coverpoint defined. It is present in the rv32i_m test only by change. If we are looking at particular values to be present in any of the operands, we should not be looking at the `op*val` in the tests. We should be looking at the coverpoints file to see what particular coverpoints are missing because in the end its the coverpoints which matter(and drive CTG). 

> 
> But, looking at the code, both rs1 and rs2 should have generated a test
> for every integer in the range -10..10.

Are you talking about the CTG code here? Cause I don't see the coverpoints for these in the coverage yaml itself. 

> 
> Even if it did, though, there's no guarantee it would have paired that with
> the max negative number.

Yes. You are right. If we want it to be paired with the max negative number, the coverpoint should look like
` rs1_val == <max_negative_number> and rs2_val == -1`. If for a particular coverpoint, no condition is defined over one of the operands, a random value is assigned which may or may not satisfy another coverpoint defined over that operand register.

**Comment by allenjbaum** [comment]
I was looking at the definition of gen_sign_dataset
 in riscv_ctg/constants.py
and
rs2_val_data: 'gen_sign_dataset(xlen) + gen_sp_dataset(xlen,True)
in the *div* definition    in riscv_ctg/data/imc.yaml

**Comment by pawks** [comment]
Those are just the datasets which define the domain for each of the variables. In the end only the cases covered by the coverpoints will be present in the tests. You should look at the coverage yaml file under the releases folder in the drive and the corresponding function definitions in the riscv-isac/cgf_normalise.py

**Comment by neelgala** [comment]
This will require updating the coverpoints in the cgf files for the div operations. This is similar to #306 and can be clubbed with that issue.

**Comment by allenjbaum** [comment]
Well, the #306 issue is probably more general than divide, so at some point
(only if we're going through the exercise of regenerating tests for some
reason) we should think about updating other tests as well,

**Comment by alitariq4589** [comment]
@davidharrishmc @allenjbaum @pawks This issue is resolved (by regenerating tests) in #365 of riscv-arch-test and the riscv-ctg related PR through which the test is generated is [this](https://github.com/riscv-software-src/riscv-ctg/pull/65).

**Comment by allenjbaum** [comment]
Pull 365 has which fixes this has been merged, so closing it.
