### ISSUE TITLE
is riscv-arch-test encoding.h out of date?

### ISSUE THREAD

**Issue by dansmathers** [riscv-non-isa/riscv-arch-test#360]
see pull #350 
I'm trying to add the CLIC CSRs to encoding.h but it looks like the riscv-arch-test encoding.h might just be out-of-date and should be updated with encoding.h at: https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/encoding.h ?
that encoding.h already has the clic CSRs included.

**Comment by allenjbaum** [comment]
This is a known problem. This should be updated on a more regular basis (automatically)

**Comment by neelgala** [comment]
All encoding.h variants are created using the [riscv-opcodes repo](https://github.com/riscv/riscv-opcodes). As discussed in the ACT-SiG. The encoding.h checked into riscv-arch-test repo should undergo a change only if a test requires that change. Spuriously updating the encoding.h alone will cause a lot of unwanted churn with no real benefits. 

If you are writing tests for CLIC, then the PR contributing those tests should include an update of the encoding.h as well since those tests require those.

**Comment by dansmathers** [comment]
Are you sure you don't want to just update it to a newer version from the repo?  It seems pretty out of date.  I think I dont see any of the new CSRs defined in priv 1.12: mconfigptr, mseccfg, mseccfgh, menvcfg, henvcfg, senvcfg, menvcfgh, henvcfgh.   So the current state of encoding.h is something between 1.11 and 1.12?

**Comment by allenjbaum** [comment]
I think the comment was that if you find something missing from the version
in the repo, don't just fix that one thing; pull-in the latest version for
your commit instead of making one-off changes. We need to document this
somewhere (I think in the test-developer spec that I've start to write, but
maybe contributor guideline

**Comment by neelgala** [comment]
@dansmathers yes you are right.. the encoding.h in this repo is pretty old - but its exactly what the current test-suites require. Enabling isolated updates of the encoding.h will lead to a lot of unnecessary updates in this repo without actual usage/contribution within the test-suites themselves. Hence the decision to avoid this at the moment.
