### ISSUE TITLE
Usage of tohost/fromhost should be removed

### ISSUE THREAD

**Issue by debs-sifive** [riscv-non-isa/riscv-arch-test#40]
From the [TestFormatSpec](https://github.com/riscv/riscv-compliance/blob/master/spec/TestFormatSpec.adoc):

> Tests shall not depend on tool specific features. For example test shall avoid usage of internal GCC macros (e.g. __risc_xlen), specific syntax (char 'a' instead of 'a) or **simulator features (e.g. tohost) etc.**

The environment files, such as [p/riscv_test.h](https://github.com/riscv/riscv-compliance/blob/8dac5e5d3d498eaf576611ce69c2307968cf96e3/riscv-test-env/p/riscv_test.h#L141) and [linkers](https://github.com/riscv/riscv-compliance/blob/8dac5e5d3d498eaf576611ce69c2307968cf96e3/riscv-test-env/p/link.ld#L9) all use `tohost`. I am curious if, in the future, this will be changed for compatibility with targets that do not use `tohost` and `fromhost`, or if there's some other workaround for this.

An example of a test currently affected by `tohost` functionality is [scall.S](https://github.com/riscv/riscv-compliance/blob/master/riscv-test-suite/rv32mi/rv64si/scall.S).

**Comment by debs-sifive** [comment]
After digging around a bit more, the privileged spec states:

> The ECALL instruction is used to make a request to the supporting execution environment.

Which begs the question of whether or not it is appropriate for the compliance tests to be testing `ecall` and related instructions, since the current test behavior expects certain behavior from the execution environment.

**Comment by allenjbaum** [comment]
IT is appropriate that code that executes privileged instructions or will
cause traps to a privileged mode or touches privileged resources (CSRs) be
in a compliance test suite - just not in the unprivileged tests suite....

We do need to start working on ensuring the framework has all the tests
required for executing privileged tests, including being able to load
handlers along with the tests themselves.

**Comment by debs-sifive** [comment]
Thanks for the clarification, Allen! Is there anything formalized/written up about how un/privileged/debug tests are going to be organized in the future?

My other concern is that users don't seem to have a documented way to override the linker/environment header files, and I think it makes more sense if users do have this ability. Right now, I think the only way to change these is through modifying the `Makefile.include` files in the target directories, but I don't know if this is the intended use of the `Makefile.include`.

**Comment by allenjbaum** [comment]
I can't comments overriding header files, but  priv mode test organization
is a discussion that should occur in the task group meetings (or starting
here in group email) sooner, rather than later, based on a recent email
discussing available products:

> There are at least the following RISC-V products available:
>
> OpenISA Vegaboard         https://open-isa.org/
> SiFive HiFive1                  https://www.crowdsupply.com/sifive/hifive1
> Kendryte KD233
https://www.analoglamb.com/product/dual-core-risc-v-64bit-k210-ai-board-kendryte-kd233/
> SiFive HiFive Unleashed
https://www.crowdsupply.com/sifive/hifive-unleashed
>
> The first two are microcontrollers, the last two can run Linux.

The Kendryte KD210 (KD233 seems to be the name of a board) is missing
interrupt and exception delegation, and seems to have a buggy
implementation of the satp register, making it impossible to run normal
S-mode Linux.
 I've been pondering an M-mode nommu Linux port, but thatis not exactly
what people mean when they talk of a Linux-capable CPU.

**Comment by debs-sifive** [comment]
My core questions regarding organization are:
- What does the TG require from a product's testing team to allow the team to say that they pass compliance tests? I.e., how much of their own background test environment/infrastructure/startup code/etc. can be used by testers?
- What is the minimum amount of test infrastructure the compliance repo can supply? So for unprivileged tests, I think it should be "enough" to supply only the test code, but for privileged or debug tests, the repo may want to specify some test environment behaviors (such as trap handling).

Perhaps through answering these questions, we can clear up the API for the compliance tests and better understand what is (un)necessary to provide with privileged tests.

**Comment by allenjbaum** [comment]
You are almost correct: there is little that needs to be supplied for the
unprivileged tests EXCEPT FOR the standard test macro support (e.g. to load
a binary, to start execution, to end test execution and report results,
etc.)
You are also correct that for the priv mode tests, interrupt and trap
handlers, possibly including emulation libraries, will need to be supplied.
Some of those are test specific (that is, they are actually part of the
test), but others  are platform and vendor specific, so should be supplied
by the vendor.
I actually don't know how those are linked into the test supplied handlers.
Obviously, the tests will use vendor infrastructure (especially DRAM), and
the physical addresses must be communicated to the test environment.

**Comment by allenjbaum** [comment]
I think all of the above is handled in riscof, so please check out their docs and let me know if you agree.

**Comment by allenjbaum** [comment]
There is a lot to unpack here. These answers refer to v2.0 of the framework+tests
The v2.x0 tests are only base ISA tests + C-ext + M-ext
The only privileged instructions currently used are those associated with the trap handler, primarily for misaligned load/store/fetch , ECALL and EBREAK instructions.

 In the v2.x framework, references to tohost/fromhost are only used in the RVTEST_CODE_BEGIN_OLD and RVTEST_CODE_END_OLD macros which are only called from env/p/riscv.h that is also deprecated and not used. These macros are deprecated and are not used in the new tests; the exist only for if someone is trying to get their custom model to work with new framework. The v2.x target files have been updated to match, and won't use them.
The env/p directory isn't needed at all since all its needed features are encapsulated in the standard macros every test uses. The /pm, /pt, and /v directories are only used for priv level tests, so they aren't used either.
We will be either replace or rewrite them as we get to priv level tests


V2.x has a standard trap handler (which will be per-mode), whose primary function is to clear interrupts (if that is what caused the trap), store all trap related CSRs into the test signature, and return to the next 8B boundary after the instruction that caused the trap. ECALL/EBREAK instructions will simply save that information and return - the trap handler does all the work.

V2.x has more documentation files with examples, including linker scripts.
The test format spec documents explains which macros must be provided by the target, and how test directories are structured. 

Let me know if this settles your concerns

**Comment by allenjbaum** [comment]
DUT can supply this if needed, but no longer referred to in arch_test.h
