### ISSUE TITLE
Issue from Arch_test.h

### ISSUE THREAD

**Issue by JAYANTH-IITM** [riscv-non-isa/riscv-arch-test#543]
Hi @UmerShahidengr @Abdulwadoodd , 

When running ACT tests for Zcmp and Zcmt , I am getting error in RVTEST_CODE_BEGIN and in RVTEST_SIGBASE
if I comment out .option rvc and .option norvc , which wasn't previously , the test is passing and I am getting expected coverage , the error is attched below for reference .

![Screenshot from 2024-10-23 20-22-24](https://github.com/user-attachments/assets/a5d4c2c7-2b71-4eb6-a672-b2ea67ec29e4)

**Comment by allenjbaum** [comment]
For which files are you commenting out .option rvc/norvc?
These are compressed tests, so the tests (and not CODE_BEGIN/SIGBASE)
should explicitly perform
 .push;.option rvc at the beginning, and a .pop at the end, if I remember
the syntax correctly.
Initialization code defaults to .norvc, if I recall correctly.

**Comment by JAYANTH-IITM** [comment]
Sir , I have commented out .option rvc/norvc for my zcmp and zcmt tests

**Comment by allenjbaum** [comment]
please send a URL to the test code; I don't see it in the dev repo

**Comment by JAYANTH-IITM** [comment]
[https://github.com/JAYANTH-IITM/riscv-arch-test/tree/Zcmp_Zcmt](https://github.com/JAYANTH-IITM/riscv-arch-test)
https://github.com/JAYANTH-IITM/ACT_Test_Reports
https://github.com/JAYANTH-IITM/ACT_Generated_Tests

**Comment by JAYANTH-IITM** [comment]
@allenjbaum @UmerShahidengr can you please help me here

**Comment by allenjbaum** [comment]
I'm stumped. This temporarily allows generation of compressed ops, aligns
the code to a 32B address, then disallows it again.
If this code is entered at a halfword aligned location, this enables the
tools to generate a c.noop to get it aligned to a 4B boundary,
enabling it to get aligned to a 32B boundary with regular noops.

If the code is already aligned to a 4B boundary, it should have no effect.
I really don't see how this should affect your test at all.

Note that these are compressed ops, and your tests start with
    RVTEST_ISA("RV64I_Zca_Zcmt").
Maybe the problem is that you should be using
   RVTEST_ISA("RV64IC_Zca_Zcmt").

without that, it may be the case that your tests are not assuming
compressed ops can be generated?

**Comment by JAYANTH-IITM** [comment]
Include 'C' in my ISA (RV32IC_Zca_Zcmp) , yet the error exists . 
![Screenshot from 2024-10-28 10-17-24](https://github.com/user-attachments/assets/32eecad6-bb2b-43fd-a55e-f5ac6aa41ad4)

**Comment by allenjbaum** [comment]
The only thing left that I can think of is you're using a version of the
toolchain (including Sail) which doesn't support those extensions.
If that doesn't work I am not sure how to proceed.

**Comment by JAYANTH-IITM** [comment]
yes umer , I will use the updated toolchain and redo the test . Thanks !

**Comment by JAYANTH-IITM** [comment]
@allenjbaum @UmerShahidengr This was indeed a toolchain issue , now fixed !
